# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

def select_ok(*coroutines) -> typing.Any:
    r"""
    Polls passed coroutines until either one of them returns successfully, or all of them have failed.
    
    Example:
    ```python
    import asyncio
    import bombardx
    
    async def ok():
        await asyncio.sleep(1)
        return
    
    async def fail():
        raise RuntimeError
    
    _ = bombardx.select_ok(ok(), fail())
    ```
    """

